name: perfect8_app
description: Perfect8 Frontend Application
version: 1.0.0

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & API
  http: ^1.1.0

  shared_preferences: ^2.2.0 # Spara JWT token lokalt
  
  # State management (välj EN)
  provider: ^6.1.0        # Enkel, rekommenderad
  # riverpod: ^2.4.0      # Alternativ
  # bloc: ^8.1.0          # Alternativ
  
  # JSON
  json_annotation: ^4.8.0
  
  # Secure storage för tokens
  flutter_secure_storage: ^9.0.0
  
  # Image picker
  image_picker: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0